### ISSUE TITLE
stage package not found

### ISSUE THREAD

**Issue by sundyCoder** [Acmece/rl-collision-avoidance#11]
CMake Error at stage_ros-add_pose_and_crash/CMakeLists.txt:17 (find_package):
  By not providing "Find stage.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "stage", but
  CMake did not find one.

  Could not find a package configuration file provided by "stage" with any of
  the following names:

    stageConfig.cmake
    stage-config.cmake

**Comment by Acmece** [comment]
Hi @sundyCoder 

Please try,
```
sudo apt-get install ros-kinetic-stage
```
