### ISSUE TITLE
Segmentation fault (core dumped) problem

### ISSUE THREAD

**Issue by CzJaewan** [Acmece/rl-collision-avoidance#12]
Hello. In order to learn with two different policies, I opened 2 mpis and tried to learn a total of 7 agents at once.

- $ rosrun stage_ros_add_pose_and_crash  stageros -u /home/nscl/rl_ws/src/RLCA_trainning/worlds/servingbot_agent.world 
- $ mpiexec -np 3 python ppo_stage.py 
- $ mpiexec -np 4 python ppo_stage.py 

In the process, a segemtation fault (core dumped) occurs.

- Segmentation fault (core dumped)

Do you know a solution to this?.

Learning proceeds from 300 episodes to 1000 episodes, but an error always occurs after that.

**Comment by Acmece** [comment]
I have run into the error before. I am sorry to say that I didn't dig into more about it. Hope you can fix it!

**Comment by George-Chia** [comment]
I met the problem too!

**Comment by BingHan0458** [comment]
I met the problem too!

**Comment by BingHan0458** [comment]
> Hello. In order to learn with two different policies, I opened 2 mpis and tried to learn a total of 7 agents at once.
> 
> * $ rosrun stage_ros_add_pose_and_crash  stageros -u /home/nscl/rl_ws/src/RLCA_trainning/worlds/servingbot_agent.world
> * $ mpiexec -np 3 python ppo_stage.py
> * $ mpiexec -np 4 python ppo_stage.py
> 
> In the process, a segemtation fault (core dumped) occurs.
> 
> * Segmentation fault (core dumped)
> 
> Do you know a solution to this?.
> 
> Learning proceeds from 300 episodes to 1000 episodes, but an error always occurs after that.

How did you solve it?

**Comment by Acmece** [comment]
Pease refer to [this issue](https://github.com/Acmece/rl-collision-avoidance/issues/2)
