### ISSUE TITLE
Query on Training the Policy

### ISSUE THREAD

**Issue by gwhan98** [Acmece/rl-collision-avoidance#15]
When training from scratch in stage 1, I am not able to get the policy to converge to the optimal policy, even after training for 10 hours. Is there a way to do a bit of supervised learning initially to form the basic framework for the policy, so that the DRL algorithm does not have to fly blind when training?  

Thank you very much for your time.

**Comment by gwhan98** [comment]
The training after 10 hours is mostly time outs and a bit of Reach goals sprinkled in between. "Optimal Policy" as in the policy that you gave with the code.

**Comment by Acmece** [comment]
A Curriculum Learning paradigm is employed in this project, please refer to [this issue](https://github.com/Acmece/rl-collision-avoidance/issues/3)

> You should start with training in Stage1 and when it is well-trained you can transfer to Stage2 using the model of Stage1, this is exactly what Curriculum Learning means. Training Stage2 from scratch may converge at a lower performance or not even converge.
Please note that the motivation of training in Stage2 is to generalize the model, which hopefully can work well in real environment.

**Comment by BingHan0458** [comment]
Hello @gwhan98  ,
Recently, I've been training this code, and I see here you say that you train it for about 10 hours, and I want to know what results in Terminal or in GUI can be shown to prove that the policy has been trained well?
And how to get the result such as success rate and extra time and so on in Table II (in [paper)](https://arxiv.org/abs/1709.10082) by code or by doing some calculations?
I hope you can give me some advice, thank you very much!
