### ISSUE TITLE
Implementation of the code with only single robot

### ISSUE THREAD

**Issue by sg774** [Acmece/rl-collision-avoidance#5]
Thank you for this open source implementation. I wanted to train this model for only one robot instead of a team of robots. Is it possible to do so? In that case what variables do I need to change? Is changing the value associated with the variable 'NUM_ENV' to 1 enough or will I be required to make other changes as well?

**Comment by Acmece** [comment]
Yes, that will work without any change. But you need to add more obstacles in the free space in order to training agents. In essence, we use multi-robots for the acceleration of training and the simulation of the dynamic environment.

**Comment by sg774** [comment]
Thank you.
