### ISSUE TITLE
Hyperparmeters values are different from the paper

### ISSUE THREAD

**Issue by afakharany93** [Acmece/rl-collision-avoidance#6]
Hello,
I have noticed that there is a difference in some hyper-parameters values between this implementation and the paper, is there a justification for that?
For an example the coefficient multiplied by the value loss in the paper is 1.0 while in your implementation it's 20.0.
Also I would like to ask if this is the official repo for the paper or is it your attempt at reimplementing the paper?
Thanks and enjoy the holidays

**Comment by Acmece** [comment]
Hi,
This is not the official repo for the paper. I reimplemented it using the clipped surrogate objective instead of KL divergence.
