### ISSUE TITLE
Error compiling code

### ISSUE THREAD

**Issue by priyablue** [Acmece/rl-collision-avoidance#7]
priya@ros:~/qlearning_ws$ rosrun stage_ros_add_pose_and_crash stageros -g worlds/stage1.world
[FATAL] [1585235899.273644693]: The world file worlds/stage1.world does not exist.
[FATAL] [1585235899.274600526]: BREAKPOINT HIT
	file = /home/priya/qlearning_ws/src/stage_ros-add_pose_and_crash/src/stageros.cpp
	line=333

Can you hep me why is this error??

**Comment by Acmece** [comment]
Please `cd` into `THE_PATH_TO/rl-collison-avoidance`.
After that, there should be no prolem.

**Comment by priyablue** [comment]
Fine thanks.. its working .. but torch is installed, but still i am getting error. 

Traceback (most recent call last):
  File "ppo_stage1.py", line 7, in <module>
    import torch
ImportError: No module named torch
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10077,1],2]
  Exit code:    1

**Comment by Acmece** [comment]
I am guessing you installed torch on Python3. Could you please check that if you have installed torch on Python2.7?
